import { SCAN_MODES } from "./scanModes";
import type { ScanResponse } from "./types";

const EMPTY_VALUE = "Not provided.";
const EMPTY_LIST_ITEM = "No items returned.";
const LIMITATIONS =
  "This report is generated by AI systems and may be incomplete or wrong. " +
  "It does not browse the web, verify facts, or provide legal, medical, " +
  "financial, security, or compliance advice. Use it as structured risk " +
  "analysis support and validate important findings with qualified human review.";
const PROVIDER_KEY_ASSIGNMENT = new RegExp(
  `\\b(${["OPENAI", "GEMINI"].map((name) => `${name}_API_KEY`).join("|")})` +
    "\\s*=\\s*[^\\s]+",
  "gi",
);
const OPENAI_KEY_PATTERN = new RegExp(
  "\\b" + "sk" + "-[A-Za-z0-9_-]{12,}\\b",
  "g",
);
const GEMINI_KEY_PATTERN = new RegExp(
  "\\b" + "AI" + "za[A-Za-z0-9_-]{20,}\\b",
  "g",
);

export function buildMarkdownReport(
  result: ScanResponse,
  exportedAt: Date = new Date(),
): string {
  const scanModeLabel =
    SCAN_MODES.find((mode) => mode.id === result.scan_mode)?.label ??
    "Unknown Scan Mode";
  const scanner = result.scanner_report;
  const auditor = result.audit_report;
  const models = result.models_used;

  return [
    "# Mythadis Faultline Report",
    "",
    "## Metadata",
    "",
    metadataLine("App", "Mythadis Faultline"),
    metadataLine("Tagline", "Find the crack before the collapse."),
    metadataLine("Exported At", exportedAt.toISOString()),
    metadataLine("Scan Mode", result.scan_mode),
    metadataLine("Scan Mode Label", scanModeLabel),
    metadataLine(
      "Primary Scanner",
      `${models.scanner_provider} / ${models.scanner_model}`,
    ),
    metadataLine(
      "Auditor",
      `${models.auditor_provider} / ${models.auditor_model}`,
    ),
    metadataLine("Scanner Risk Level", scanner.risk_level),
    metadataLine("Auditor Confidence", auditor.auditor_confidence),
    "",
    "## Original Input",
    "",
    safeText(result.input),
    "",
    "## Scan Mode",
    "",
    `${safeText(scanModeLabel)} (\`${safeText(result.scan_mode)}\`)`,
    "",
    "## Models Used",
    "",
    metadataLine(
      "Primary Scanner",
      `${models.scanner_provider} / ${models.scanner_model}`,
    ),
    metadataLine(
      "Auditor",
      `${models.auditor_provider} / ${models.auditor_model}`,
    ),
    "",
    "## Faultline Report",
    "",
    textSection("Faultline Summary", scanner.faultline_summary),
    textSection("Surface Claim", scanner.surface_claim),
    listSection("Hidden Assumptions", scanner.hidden_assumptions),
    listSection("Pressure Points", scanner.pressure_points),
    listSection("Collapse Risks", scanner.collapse_risks),
    listSection("Weak Evidence", scanner.weak_evidence),
    listSection("What Would Break This", scanner.what_would_break_this),
    listSection("Validation Tests", scanner.validation_tests),
    listSection(
      "Questions Before Commitment",
      scanner.questions_before_commitment,
    ),
    textSection("Risk Level", scanner.risk_level),
    textSection("Recommended Next Move", scanner.recommended_next_move),
    "## Second-AI Audit Review",
    "",
    textSection("Audit Summary", auditor.audit_summary),
    listSection("Missed Risks", auditor.missed_risks),
    listSection("Weak or Vague Findings", auditor.weak_or_vague_findings),
    listSection("Validation Plan Gaps", auditor.validation_plan_gaps),
    textSection("Risk Level Challenge", auditor.risk_level_challenge),
    listSection(
      "Recommended Report Improvements",
      auditor.recommended_report_improvements,
    ),
    textSection("Auditor Confidence", auditor.auditor_confidence),
    textSection("Final Caution", auditor.final_caution),
    "## Limitations",
    "",
    LIMITATIONS,
    "",
  ].join("\n");
}

export function buildMarkdownFilename(exportedAt: Date = new Date()): string {
  const timestamp = exportedAt
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\.\d{3}Z$/, "Z")
    .replace("T", "-")
    .replace("Z", "");
  return `mythadis-faultline-report-${timestamp}.md`;
}

function metadataLine(label: string, value: unknown): string {
  return `- ${label}: ${safeText(value)}`;
}

function textSection(title: string, value: unknown): string {
  return `### ${title}\n\n${safeText(value)}\n`;
}

function listSection(title: string, values: unknown): string {
  return `### ${title}\n\n${formatList(values)}\n`;
}

function formatList(values: unknown): string {
  if (!Array.isArray(values) || values.length === 0) {
    return `- ${EMPTY_LIST_ITEM}`;
  }

  const items = values
    .map((value) => safeText(value))
    .filter((value) => value !== EMPTY_VALUE);

  return items.length > 0
    ? items.map((item) => `- ${item}`).join("\n")
    : `- ${EMPTY_LIST_ITEM}`;
}

function safeText(value: unknown): string {
  if (typeof value !== "string" && typeof value !== "number") {
    return EMPTY_VALUE;
  }

  const text = String(value).trim();
  if (!text) {
    return EMPTY_VALUE;
  }

  return redactSecrets(text);
}

function redactSecrets(value: string): string {
  return value
    .replace(PROVIDER_KEY_ASSIGNMENT, "[redacted provider key]")
    .replace(OPENAI_KEY_PATTERN, "[redacted provider key]")
    .replace(GEMINI_KEY_PATTERN, "[redacted provider key]");
}
